
import io
import os
from datetime import datetime

# ReportLab imports for PDF
try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

# python-docx imports for Word
try:
    from docx import Document as DocxDocument
    from docx.shared import Pt, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False


def generate_pdf_from_markdown(markdown_content: str, title: str = "Document") -> bytes:
    """
    Generate PDF from markdown-like content using ReportLab.
    Windows-compatible alternative to WeasyPrint.
    
    Args:
        markdown_content: Markdown string to convert
        title: Document title for header
    
    Returns:
        PDF file as bytes
    """
    if not REPORTLAB_AVAILABLE:
        raise ImportError("reportlab is not installed. Run: pip install reportlab")
    
    # Create PDF buffer
    buffer = io.BytesIO()
    
    # Setup document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72
    )
    
    # Styles
    styles = getSampleStyleSheet()
    
    # Custom title style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor='#2c5530',  # Agrico Hub green
        alignment=TA_CENTER,
        spaceAfter=12
    )
    
    # Custom header style
    header_style = ParagraphStyle(
        'CustomHeader',
        parent=styles['Heading2'],
        fontSize=14,
        textColor='#2c5530',
        spaceAfter=6
    )
    
    # Build content
    story = []
    
    # Title
    story.append(Paragraph(f"<b>{title}</b>", title_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Metadata
    meta_text = f"<i>Generated by Agrico Hub SSDP | {datetime.now().strftime('%Y-%m-%d')}</i>"
    story.append(Paragraph(meta_text, styles['Normal']))
    story.append(Spacer(1, 0.3*inch))
    
    # Parse markdown-like content
    lines = markdown_content.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.15*inch))
            continue
        
        # Headers
        if line.startswith('# '):
            story.append(Paragraph(f"<b>{line[2:]}</b>", header_style))
        elif line.startswith('## '):
            story.append(Paragraph(f"<b><i>{line[3:]}</i></b>", styles['Heading3']))
        elif line.startswith('### '):
            story.append(Paragraph(f"<i>{line[4:]}</i>", styles['Normal']))
        # Bullet points
        elif line.startswith('- ') or line.startswith('* '):
            story.append(Paragraph(f"• {line[2:]}", styles['Normal']))
        # Bold text
        elif '**' in line:
            formatted = line.replace('**', '<b>').replace('</b>', '</b>')
            story.append(Paragraph(formatted, styles['Normal']))
        # Regular text
        else:
            story.append(Paragraph(line, styles['Normal']))
    
    # Add page break and footer
    story.append(PageBreak())
    footer = Paragraph(
        "<i>Generated by Agrico Hub Startup & Scale-Up Digital Platform</i>",
        ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, alignment=TA_CENTER)
    )
    story.append(footer)
    
    # Build PDF
    doc.build(story)
    
    # Get bytes
    buffer.seek(0)
    return buffer.getvalue()


def generate_docx_from_markdown(markdown_content: str, title: str = "Document") -> bytes:
    """
    Generate Docx from markdown-like content.
    
    Args:
        markdown_content: Markdown string to convert
        title: Document title
    
    Returns:
        Docx file as bytes
    """
    if not DOCX_AVAILABLE:
        raise ImportError("python-docx is not installed. Run: pip install python-docx")
    
    doc = DocxDocument()
    
    # Add title
    heading = doc.add_heading(title, 0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Add metadata
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta.add_run(f"Generated by Agrico Hub SSDP | {datetime.now().strftime('%Y-%m-%d')}").italic = True
    doc.add_paragraph()  # Spacer
    
    # Parse markdown-like content
    lines = markdown_content.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            doc.add_paragraph()  
            continue
        
        # Headers
        if line.startswith('# '):
            doc.add_heading(line[2:], level=1)
        elif line.startswith('## '):
            doc.add_heading(line[3:], level=2)
        elif line.startswith('### '):
            doc.add_heading(line[4:], level=3)
        # Bullet points
        elif line.startswith('- ') or line.startswith('* '):
            p = doc.add_paragraph(style='List Bullet')
            p.add_run(line[2:])
        # Numbered lists
        elif line[0].isdigit() and line[1] == '.':
            p = doc.add_paragraph(style='List Number')
            p.add_run(line[2:])
        # Regular text
        else:
            doc.add_paragraph(line)
    
    # Add footer
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.add_run("Generated by Agrico Hub Startup & Scale-Up Digital Platform").italic = True
    
    # Save to bytes
    docx_file = io.BytesIO()
    doc.save(docx_file)
    docx_file.seek(0)
    
    return docx_file.getvalue()