# Simple template engine for FR-10 (placeholder for AI integration in FR-12)

TEMPLATES = {
    'business_plan': """
# {{title}}

## Executive Summary
{{executive_summary}}

## Business Description
- **Industry**: {{industry}}
- **Target Market**: {{target_market}}
- **Business Model**: {{business_model}}

## Market Analysis
{{market_analysis}}

## Financial Projections
{{financial_projections}}

## Next Steps
{{next_steps}}

---
*Generated by Agrico Hub SSDP*
    """,
    
    'pitch_deck': """
# {{title}} - Pitch Deck Outline

## Slide 1: Problem
{{problem_statement}}

## Slide 2: Solution
{{solution_description}}

## Slide 3: Market Opportunity
- TAM: {{tam}}
- SAM: {{sam}}
- SOM: {{som}}

## Slide 4: Business Model
{{revenue_model}}

## Slide 5: Traction
{{traction_metrics}}

## Slide 6: Ask
{{funding_ask}}

---
*Generated by Agrico Hub SSDP*
    """,
    
    'sop': """
# Standard Operating Procedure: {{title}}

## Purpose
{{purpose}}

## Scope
{{scope}}

## Responsibilities
{{responsibilities}}

## Procedure Steps
{{procedure_steps}}

## References
{{references}}

---
*Generated by Agrico Hub SSDP*
    """
}


def generate_document(doc_type: str, inputs: dict) -> str:
    """
    Generate document content from template + user inputs.
    This is a placeholder for AI integration (FR-12).
    
    Args:
        doc_type: Type of document ('business_plan', 'pitch_deck', 'sop')
        inputs: Dictionary of values to substitute into template
    
    Returns:
        Generated document content as string
    """
    template = TEMPLATES.get(doc_type)
    if not template:
        raise ValueError(f"Unknown document type: {doc_type}")
    
    # Simple template substitution: {{key}} → inputs[key]
    content = template
    for key, value in inputs.items():
        content = content.replace(f"{{{{{key}}}}}", str(value))
    
    return content.strip()